import { test, expect } from '@playwright/test';
import { seed } from '../../src/data/seed';
async function addSimple(page: import('@playwright/test').Page) {
  await page.goto('/producto/pulsera-luna'); await page.getByRole('button', { name: 'Agregar a mi bolsa', exact: true }).click();
  await page.getByRole('link', { name: /Mi bolsa, 1 productos/ }).click();
}
test('complete delivery and pickup flow, validation, variants, persistence and message', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Tu esencia');
  await page.locator('main').getByRole('link', { name: 'Explorar accesorios', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Buscar accesorios' }).fill('Aretes Sol');
  await expect(page.locator('.product-card')).toHaveCount(1);
  await page.getByRole('link', { name: 'Aretes Sol', exact: true }).click();
  await page.getByRole('button', { name: 'Agregar a mi bolsa', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Selecciona color');
  await page.getByRole('radio', { name: 'Dorado', exact: true }).check();
  await page.getByRole('button', { name: 'Agregar a mi bolsa', exact: true }).click();
  await page.getByRole('link', { name: /Mi bolsa, 1 productos/ }).click();
  await page.getByRole('button', { name: 'Aumentar cantidad de Aretes Sol' }).click();
  await expect(page.locator('.summary-total')).toContainText('$44.800');
  await page.reload();
  await expect(page.locator('.summary-total')).toContainText('$44.800');
  await page.getByRole('link', { name: 'Continuar con mi pedido' }).click();
  await page.getByRole('button', { name: 'Revisar mi pedido' }).click();
  await expect(page.getByRole('alert')).toContainText('Elige cómo recibir');
  await page.getByRole('radio', { name: /Envío a domicilio/ }).check();
  await page.getByRole('button', { name: 'Revisar mi pedido' }).click();
  await expect(page.getByText('Escribe tu nombre completo.')).toBeVisible();
  await page.getByLabel(/^Nombre completo/).fill('Cliente de prueba');
  await expect(page.getByLabel('Ciudad', { exact: true })).toHaveValue('Cali');
  await expect(page.getByLabel('Departamento', { exact: true })).toHaveValue('Valle del Cauca');
  await page.getByLabel(/^Barrio/).fill('Barrio de prueba');
  await page.getByLabel(/^Dirección/).fill('Dirección de prueba');
  await page.getByLabel(/Conjunto, edificio/).fill('Torre de prueba');
  await page.getByLabel(/Indicaciones de entrega/).fill('Indicación de prueba');
  await page.getByLabel(/Comentarios del pedido/).fill('Comentario & detalle');
  await page.getByRole('button', { name: 'Revisar mi pedido' }).click();
  await expect(page.getByRole('heading', { name: 'Revisa tu pedido' })).toBeVisible();
  await expect(page.locator('address')).toContainText('Dirección de prueba');
  await page.getByRole('button', { name: /Preparar WhatsApp|Volver a verificar pedido/ }).click();
  await expect(page.getByRole('link', { name: 'Abrir WhatsApp', exact: true })).toHaveAttribute('href', /^https:\/\/wa\.me\/573150026236\?text=/);
  await page.getByText('Ver mensaje completo').click();
  const message = page.getByRole('textbox', { name: 'Mensaje completo del pedido' });
  await expect(message).toContainText('Torre de prueba');
  await expect(message).toContainText('Indicación de prueba');
  await expect(message).toContainText('Compras al por mayor a partir de $50.000');
  await expect(message).toContainText('$44.800');
  await page.getByRole('link', { name: 'Modificar mis datos' }).click();
  await page.getByRole('radio', { name: /Recoger en el local/ }).check();
  await expect(page.getByLabel('Dirección', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel(/^Nombre completo/)).toHaveValue('Cliente de prueba');
  await page.getByRole('button', { name: 'Revisar mi pedido' }).click();
  await expect(page.locator('address')).toHaveCount(0);
  await page.getByRole('button', { name: /Preparar WhatsApp|Volver a verificar pedido/ }).click();
  await page.getByText('Ver mensaje completo').click();
  await expect(message).toContainText('EL PEDIDO SERÁ RECOGIDO EN EL LOCAL');
  await expect(message).not.toContainText('Dirección de prueba');
  const storage = await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }));
  expect(storage).not.toContain('Cliente de prueba'); expect(storage).not.toContain('Dirección de prueba');
  await page.reload();
  await expect(page).toHaveURL(/checkout$/);
  await page.getByRole('radio', { name: /Recoger en el local/ }).check();
  await expect(page.getByLabel(/^Nombre completo/)).toHaveValue('');
});
test('categories, sort, no results, inactive, image fallback and empty cart', async ({ page }) => {
  await page.goto('/catalogo?categoria=anillos');
  await expect(page.locator('.product-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Todos los accesorios', exact: true }).click();
  await expect(page.locator('.product-card')).toHaveCount(8);
  await page.getByRole('combobox', { name: 'Ordenar por' }).selectOption('low');
  await expect(page.locator('.product-card').first()).toContainText('Pinza Duna');
  await page.getByRole('searchbox', { name: 'Buscar accesorios' }).fill('no existe este producto');
  await expect(page.getByRole('heading', { name: 'No encontramos ese detalle' })).toBeVisible();
  await page.goto('/producto/anillo-archivo'); await expect(page.getByRole('heading', { name: 'Este detalle no está disponible' })).toBeVisible();
  await page.route('**/images/bracelet.jpg', route => route.abort());
  await addSimple(page);
  await expect(page.locator('.cart-line img')).toHaveAttribute('src', '/images/fallback.svg');
  await page.getByRole('button', { name: 'Eliminar Pulsera Luna' }).click();
  await expect(page.getByRole('heading', { name: 'Tu bolsa espera un detalle' })).toBeVisible();
});
test('stale catalog and unavailable cart are safely handled', async ({ page }) => {
  await addSimple(page);
  await page.getByRole('link', { name: 'Continuar con mi pedido' }).click();
  await page.getByRole('radio', { name: /Recoger en el local/ }).check();
  await page.getByLabel(/^Nombre completo/).fill('Prueba local');
  await page.getByRole('button', { name: 'Revisar mi pedido' }).click();
  await page.evaluate(catalog => { catalog.products.find(p => p.id === 'pulsera-luna')!.wholesalePrice = 25000; localStorage.setItem('nala.catalog.v1', JSON.stringify(catalog)); }, structuredClone(seed));
  await page.getByRole('button', { name: /Preparar WhatsApp|Volver a verificar pedido/ }).click();
  await expect(page.getByRole('alert')).toContainText('El catálogo cambió');
  await expect(page.locator('.summary-total')).toContainText('$25.000');
  await page.evaluate(() => { const catalog = JSON.parse(localStorage.getItem('nala.catalog.v1')!); catalog.products.find((p: { id: string }) => p.id === 'pulsera-luna').active = false; localStorage.setItem('nala.catalog.v1', JSON.stringify(catalog)); });
  await page.goto('/carrito');
  await expect(page.getByRole('alert')).toContainText('ya no está disponible');
  await expect(page.getByRole('button', { name: 'Actualiza tu bolsa para continuar' })).toBeDisabled();
});
test('local administration manages products, options, categories and optimized photos', async ({ page }) => {
  await page.goto('/admin');
  await expect(page.getByRole('heading', { name: 'Hola de nuevo.' })).toBeVisible();
  await page.getByRole('button', { name: 'Entrar al modo local' }).click();
  await expect(page.locator('.admin-product')).toHaveCount(9);
  await page.getByRole('button', { name: 'Editar Aretes Sol', exact: true }).click();
  await page.getByLabel('Nombre del producto', { exact: true }).fill('Aretes Sol editados');
  await page.getByLabel('Precio al detal en pesos colombianos').fill('29000');
  await page.getByLabel('Precio al por mayor en pesos colombianos').fill('21000');
  await page.getByLabel('Seleccionar fotografías').setInputFiles('public/images/hero.jpg');
  await expect(page.locator('.admin-images>div')).toHaveCount(3);
  await page.getByRole('button', { name: 'Guardar producto' }).click();
  await expect(page.getByRole('heading', { name: 'Aretes Sol editados' })).toBeVisible();
  await page.getByRole('button', { name: 'Editar Aretes Sol editados', exact: true }).click();
  await expect(page.getByLabel('Precio al por mayor en pesos colombianos')).toHaveValue('21000');
  await page.getByRole('button', { name: 'Cancelar edición' }).click();
  await page.getByRole('button', { name: 'Desactivar Aretes Sol editados' }).click();
  await expect(page.getByRole('button', { name: 'Activar Aretes Sol editados', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Categorías/ }).click();
  await page.getByLabel('Nombre de la categoría').fill('Accesorios de prueba');
  await page.getByRole('button', { name: 'Guardar categoría' }).click();
  await expect(page.locator('.category-admin-row').filter({ hasText: 'Accesorios de prueba' })).toBeVisible();
  await page.getByRole('button', { name: /Productos/ }).click();
  await page.getByRole('button', { name: 'Nuevo producto' }).click();
  await page.getByLabel('Nombre del producto', { exact: true }).fill('Producto de prueba');
  await page.getByLabel('Descripción', { exact: true }).fill('Descripción del producto de prueba, únicamente para validar la tienda.');
  await page.getByLabel('Precio al detal en pesos colombianos').fill('15000');
  await page.getByLabel('Precio al por mayor en pesos colombianos').fill('12000');
  await page.getByRole('combobox', { name: 'Categoría', exact: true }).selectOption({ label: 'Accesorios de prueba' });
  await page.getByLabel('O agregar una URL de imagen').fill('/images/necklace.jpg');
  await page.getByRole('button', { name: 'Agregar imagen', exact: true }).click();
  await page.getByRole('button', { name: 'Agregar opción', exact: true }).click();
  await page.getByLabel('Nombre de la opción').fill('Tamaño');
  await page.getByLabel('Valores separados por comas').fill('Pequeño, Grande');
  await page.getByRole('button', { name: 'Guardar producto' }).click();
  await expect(page.getByRole('heading', { name: 'Producto de prueba', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
  await expect(page.getByRole('heading', { name: 'Hola de nuevo.' })).toBeVisible();
  await page.goto('/catalogo?q=Producto%20de%20prueba');
  await expect(page.locator('.product-card')).toHaveCount(1);
  await page.getByText('Producto de prueba', { exact: true }).click();
  await page.getByRole('radio', { name: 'Grande', exact: true }).check();
  await page.getByRole('button', { name: 'Agregar a mi bolsa', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'se agregó' })).toBeVisible();
});
test('product deletion requires confirmation and persists after reload', async ({ page }) => {
  await page.goto('/admin');
  await page.getByRole('button', { name: 'Entrar al modo local' }).click();
  const remove = page.getByRole('button', { name: 'Eliminar producto Aretes Sol', exact: true });
  page.once('dialog', dialog => dialog.dismiss());
  await remove.click();
  await expect(remove).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await remove.click();
  await expect(remove).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: 'Entrar al modo local' }).click();
  await expect(remove).toHaveCount(0);
  await page.goto('/producto/aretes-sol');
  await expect(page.getByRole('heading', { name: 'Este detalle no está disponible' })).toBeVisible();
});

test('responsive pages at 360, 390, 412 and desktop have no overflow or broken photos', async ({ page }, testInfo) => {
  for (const width of [360, 390, 412, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    for (const route of ['/', '/catalogo', '/producto/anillo-oliva']) {
      await page.goto(route); await page.locator('main h1').waitFor();
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    }
    await page.goto('/');
    await page.screenshot({ path: `artifacts/home-${testInfo.project.name}-${width}.png`, fullPage: true });
  }
  await page.goto('/catalogo');
  await expect.poll(() => page.locator('.product-card img').evaluateAll(images => images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBe(true);
});
