import { Search, SlidersHorizontal, X } from 'lucide-react';
import { useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useStore } from '../state/store';
import ProductCard from '../components/ProductCard';
import { ErrorState, Loading } from '../components/ui';
export default function Catalog() {
  const { products, categories, loading, error, refresh } = useStore();
  const [params, setParams] = useSearchParams(), input = useRef<HTMLInputElement>(null);
  const search = params.get('q') || '', category = params.get('categoria') || '', sort = params.get('orden') || 'featured', featured = params.get('destacados') === '1';
  useEffect(() => { if (params.get('buscar')) input.current?.focus(); }, [params]);
  function update(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next, { replace: key === 'q' }); }
  const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
  const filtered = products.filter(p => (!category || p.categoryId === category) && (!featured || p.featured) && normalize(`${p.name} ${p.description} ${categories.find(c => c.id === p.categoryId)?.name}`).includes(normalize(search))).sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : sort === 'new' ? b.createdAt - a.createdAt : Number(b.featured) - Number(a.featured));
  return <div className="container catalog-page"><div className="page-intro"><span className="eyebrow">TU PRÓXIMO FAVORITO ESTÁ AQUÍ</span><h1>{featured ? 'Los favoritos de Nala' : 'Detalles para ser tú.'}</h1><p>Elige tus favoritos y arma tu selección al por mayor. Consulta las condiciones por WhatsApp.</p></div><div className="catalog-toolbar"><label className="search-field"><Search size={20}/><span className="sr-only">Buscar accesorios</span><input ref={input} value={search} onChange={e => update('q', e.target.value)} placeholder="¿Qué detalle estás buscando?" type="search" maxLength={120}/></label><label className="sort-field"><SlidersHorizontal size={18}/><span className="sr-only">Ordenar por</span><select value={sort} onChange={e => update('orden', e.target.value)}><option value="featured">Recomendados</option><option value="low">Menor precio</option><option value="high">Mayor precio</option><option value="new">Más recientes</option></select></label></div><div className="category-pills"><button className={!category ? 'active' : ''} onClick={() => update('categoria', '')}>Todos los accesorios</button>{categories.map(c => <button key={c.id} className={category === c.id ? 'active' : ''} onClick={() => update('categoria', c.id)}>{c.name}</button>)}{featured && <button onClick={() => update('destacados', '')}>Solo favoritos <X size={14}/></button>}</div>{loading ? <Loading/> : error ? <ErrorState message={error} retry={refresh}/> : <><p className="results-count">{filtered.length} accesorios para descubrir</p>{filtered.length ? <div className="product-grid">{filtered.map(p => <ProductCard key={p.id} product={p}/>)}</div> : <section className="empty"><Search size={32}/><h2>{products.length ? 'No encontramos ese detalle' : 'Estamos preparando algo bonito'}</h2><p>{products.length ? 'Prueba con otra palabra o explora todas las categorías.' : 'Nuestro catálogo estará disponible pronto.'}</p>{products.length > 0 && <button className="button" onClick={() => setParams({})}>Ver todos los accesorios</button>}</section>}</>}</div>;
}
